export const NEW = "New";
export const IN_REVIEW = "In Review";
export const REQUESTED_CHANGES = "Requested Changes";
export const RE_UPLOADED = "Re-Uploaded";
export const APPROVED = "Approved";
export const DONE = "Done";
export const COMPLETED = "Completed";
export const ARCHIVED = "Archived";
export const DELETED = "Deleted";
